### ISSUE TITLE
[Private map] Connector panel

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/kepler.gl#11]
Create the panel & related modal to CARTO Login to establish the connection with CARTO Storage

**Comment by jesusbotella** [comment]
Can we link the related invision design in here, please? 😁

**Comment by VictorVelarde** [comment]
Sorry for the delay @jesusbotella. These are the last links that @MireyaD shared in slack.

- "Public map": https://invis.io/TPTSVDX2KF5#/384524982_Sharing_-_Home
- “Storage Maps”: https://invis.io/TPTSVDX2KF5#/389126759_Storage_V3

You can talk together in the slack channel if any change is needed

**Comment by VictorVelarde** [comment]
It's important to notice that in this first design we will just present 'Maps' (not 'Datasets') and there are 2 alternatives for the maps list: with or without thumbnails. 

The last part depends on our ability to persist the image it during the 'Save map' actions. See https://github.com/CartoDB/kepler.gl/issues/17

**Comment by VictorVelarde** [comment]
Done by @neokore
