### ISSUE TITLE
Define basic tests v0.1

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/kepler.gl#20]
**Goal:** QA testing before the PR of v0.1 in Kepler's repository.
Deadline: `4th October`

Define basic tests, according to:
- Type of Account (test with an individual account, enterprise users...)
- New (new users vs existing users)
- Several browsers

**Comment by ana-md** [comment]
On-going preparation for the testing can be found [here](https://docs.google.com/document/d/1MMC6GFY-9vtXW6fYSBA2gIjXXhTOwLbsADIccI9uvUA/edit?ts=5d95265d). 

Tasks distributed depending on users and workflows are [here](https://docs.google.com/spreadsheets/d/16TVG1qrLfQ0sDdZMbOEnA3oHlQYd4HSWPkqTxlV8K-s/edit).
