### ISSUE TITLE
Fix OAuth & Signup blockers

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/kepler.gl#22]
We have found 2 blockers for the v0.1 milestone (PR). We need to fix first these issues:

- [x] Signup: https://github.com/CartoDB/cartodb/issues/15122 
- [x] OAuth permission: https://github.com/CartoDB/support/issues/2220

Both are currently assigned to RT, to be fixed as soon as possible.

We also have a third blocker, in this case for the v0.2 milestone:

- [ ] New scope `datasets:r:*`: https://github.com/CartoDB/cartodb/issues/15130

**Comment by alrocar** [comment]
Deadlines for this?

We use to have a flood of issues in RT and maybe doing a short project could unblock these issues faster.

**Comment by VictorVelarde** [comment]
All of these were needed for the Kepler.gl project (phase I) ending this cycle. So I would say that as soon as you can 😄
 
In any case, we're going to extend the work into the next cycle, with a new project (phase II), so we can try to fit-in, maybe doing some 'ñapas' this cycle, but we do really need to get this done soon.

**Comment by alrocar** [comment]
Would it make sense joining someone from backend to that project during a couple of weeks?

**Comment by VictorVelarde** [comment]
I think that would be great! 

cc/ @ana-md check this 🔝

**Comment by ana-md** [comment]
Sure! Not sure about the amount of time days/weeks, that's you who can best scope it, but it would definitely help unlock this to move further with Kepler

**Comment by VictorVelarde** [comment]
quick status:
- Signup & the use of functions have been fixed
- For the use of FK references, a useful workaround has been applied
- New scope is still pending for next phases

**Comment by VictorVelarde** [comment]
I'm closing this, as we have just released the first phase, and we're not dealing with **datasets** listing, so we don't need yet the "New scope datasets:r:*: CartoDB/cartodb#15130

We'll reopen if this is finally needed for a future phase
