### ISSUE TITLE
Move map id to query param instead of URL part

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/kepler.gl#27]
CARTO's cloud provider has the following URL:

<host>/demo/map/carto/<mapID>?owner

We should change this to

<host>/demo/map/carto?owner=&id=

and remove the (:mapID) from the routes

**Comment by VictorVelarde** [comment]
Does the change to the URL make any internal difference or is it just a 'style' change?

**Comment by rjimenezda** [comment]
We thought it'd be more consistent with the rest of the URL. Dropbox takes advantage of a ?mapUrl, and we already need to add a query param for the owner.

**Comment by jesusbotella** [comment]
Removed `mapId` parameter from route string and adapted provider function to take it from query parameters.

`/demo/map/carto?owner=&mapId=`
