### ISSUE TITLE
[Public map] Deploy a version with Master API Key (staging) for demo video & Create demo video (v0.1)

### ISSUE THREAD

**Issue by neokore** [CartoDB/kepler.gl#28]
Part 1
- [x] Create Zeit Now Cloud environment for deploys
- [x] Upload master key branch to cloud
- [x] Document how to use it
- [x] Create small video, exemplifying 'Share with public URL'

Part 2
- ~[x] Configure CI with Zeit Now (available using GitHub)~
- [x] Test -->  app deployment not running well

**Comment by neokore** [comment]
✅ Video demo uploaded to https://drive.google.com/open?id=10q43cqR-VpR5ILY0KW-uSvFofYmQP5X4
✅ App using master key deployed to https://keplergl-share-carto.neokore.now.sh.
To get the app working you need to execute the following commands in your browser console:
```js
localStorage.setItem('carto.username', '<your_carto_username>');
localStorage.setItem('carto.server', 'https://{user}.carto.com/');
localStorage.setItem('carto.masterKey', '<your_carto_masterkey>');
```
Then refresh (just in case) and click on Share > Share public URL > CARTO

**Comment by neokore** [comment]
Waiting until we get the final now.sh environment to deploy and the OAuth issues are resolved.

**Comment by VictorVelarde** [comment]
We already have the account, but `now app` has still to be approved for the repo. https://github.com/CartoDB/companystuff/issues/3307

**Comment by VictorVelarde** [comment]
Keeping with the manual deployment to now, as CI integration (build) is not working fine
