### ISSUE TITLE
[Public map] UX improvements

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/kepler.gl#36]
From 0.1 tests, we detected:
- [ ] Improve the style of the selected provider
- [ ] Clean shared url textbox when closing window
- [ ] Change the "Upload copy"? --> have some specific copy for Carto, instead of the generic current one
- [ ] Missing icons in staging for Github / Google when using OAuth2

**Comment by ana-md** [comment]
I am closing this old issue, but @MireyaD let's keep this in mind as it came up in our previous test and: 
- If it is solved now --> OK
- If not --> Let's add it to the [QA findings summary](https://github.com/CartoDB/product/issues/542)
