### ISSUE TITLE
[Private map] UI for provider error messages

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/kepler.gl#37]
Present a UI reporting any error using the connectors

In the case of CARTO, that might include, for example:
- user has not 'engine' enabled (free users)
- out of limits
- API timeouts...

**Comment by neokore** [comment]
I've started with the basic error message design (Red text line) but now that Uber team is changing UI, let's wait until it is defined.

**Comment by neokore** [comment]
After the meeting with Uber team, we will use their notification system to show error messages

**Comment by VictorVelarde** [comment]
In the current integration some error messages appear inside the Dialog (eg. en Share  Map URL:)

Eg: 
![image](https://user-images.githubusercontent.com/458196/74645467-4859ee00-5178-11ea-866f-7df80b3609b1.png)

That can work but we should **clean** the error if it can be solved (eg deleting in CARTO the preexisting dataset and retrying). @neokore ?

**Comment by neokore** [comment]
It looks like an issue with auth info, maybe we can detect it and force the user to log into again to solve it withour errors.

**Comment by ana-md** [comment]
Can we already close this issue? or is there still anything to be done here?

**Comment by VictorVelarde** [comment]
There is still a bug (not CARTO specific), related to error messages not been cleaned. Creating a new one for prioritization

**Comment by VictorVelarde** [comment]
Closingin favour of #52
