### ISSUE TITLE
Cannot load some demos

### ISSUE THREAD

**Issue by alasarr** [CartoDB/kepler.gl#4]
When I try to load sample data -> NYC taxi trips I get:

![image](https://user-images.githubusercontent.com/1161870/62923725-aadbc700-bdae-11e9-9215-6822d1717356.png)

**Comment by rjimenezda** [comment]
That's weird, I was just able to load this. Could you try again just in case it was someting unrelated? The error is apparently totally unrelated to us.

**Comment by VictorVelarde** [comment]
Closing, not applicable to current cycle
