### ISSUE TITLE
Check Plan Limits

### ISSUE THREAD

**Issue by ana-md** [CartoDB/kepler.gl#42]
Review the account limits that affect the users joining from Kepler:

Rate limits
- [x] Check rate limits 
- [x] How to display error with COPY rate limits when user creates maps with several layers.

Quota error
- [x] How to display on UI *lack of space*

**Comment by VictorVelarde** [comment]
Please @neokore give some status

**Comment by neokore** [comment]
Current account profile *Free 2020* values
- `Carto-Rate-Limit-Limit`
    - SQL: 26
    - CopyFrom: 3
- `Carto-Rate-Limit-Reset`
    - SQL: 0
    - CopyFrom: starts with 20

Both return `Status 429` when the limit is exceeded

**Comment by neokore** [comment]
Error messages (in Toolkit):
- DB Quota:
    - CopyFrom: `Error: Failed to copy to keplergl_private_v0_tablename: DB Quota exceeded`
    - SQL: `Error: DB Quota exceeded`

- Rate limit:
    - CopyFrom: `Error: Failed to copy to keplergl_private_v0_tablename: Too many retries`
    - SQL: 
        - (In initialization) `Something went wrong initializing custom storage`
        - (In use) `Error: Too many retries`

**Comment by ana-md** [comment]
Regarding the error messages for the user:
- For the DB Quota, @MireyaD and I will align with @vdiego on the message we would like to share with the user and let you know. 
- For the COPY rate limit, we would like to understand a bit better what exactly happens with this limit: does the user reach it by having maps with too many layers? If yes, does this mean that the user waits for a long time until the map is saved? or does this mean that with so many layers they can't save it at all? Does this limit affect somewhere else? 

We just want to make sure we send the right message providing a good user experience telling them why something doesn't work and how they could fix it (if that fixes it) by upgrading their CARTO account. 
Thanks!

**Comment by neokore** [comment]
The COPY rate limit can appear when the user needs to save more than 2 or 3 **datasets** (it doesn't have nothing to do with layers as long as you can create several layers based on the same dataset). When the COPY rate limit appears we have two options:
- **Wait to this limit to be reset and try again**. Then the dataset should be saved successfully (unless another error happens, DB Quota limit reached for example). It will increase the time to save the map, but the user will be able to do it.
- **Return an error**. In this case, the user will not be able to create visualizations with more than 2 or 3 datasets.

**Comment by ana-md** [comment]
Thanks @neokore !! As far as I understood from @VictorVelarde and backend team was that, as each layer is saved as a new table, the COPY rate limit would basically limit the number of layer that the user can create and save per map. 
In this phase of the integration, for the user they are just saving maps (even if behind it, technically, we are just saving datasets). When would the user then be saving more than 2 or 3 datasets?

**Comment by neokore** [comment]
It will usually be as they told you, but I wanted to specify that sometimes you can have several layers based on the same dataset, for example, having multiple time dependant values in different columns for the same geometry, as Kepler.gl shows in their demo "Travel times from Uber movement".
Technically, our limit is set on the number of parallel (or sequencial in a certain amount of time) COPY calls you can do. And this calls are used to save datasets.

**Comment by VictorVelarde** [comment]
Sorry to be late. Yeah, as @neokore says, limits affect here to the number of calls to manage several datasets in the viz. And this 'generally' means several 'layers'. I woudl go for something like "Do you want to store maps in CARTO with several layers & datasets?, consider upgrading to..."

**Comment by MireyaD** [comment]
Hey!

I'm working on the UX at this point, but I have some doubts related to the technical limitations regarding the COPY rate limit. 

We should inform the user as clearly as possible so that they understand what's going on, and they feel they have control of what's happening behind.

My doubts here at a technical level are:

- Could we have an estimate of **how long** the process can take at the beginning? 
It does not need to be exact, it can be an estimate of how long that process usually takes.

- Would it be possible to give feedback about **what's happening** behind? 
For instance, if there are 10 steps and it's working on the 3rd one: “Completed 3 of 10. Adding _San Francisco Street Tree Map_ layer”


It would be great if you could take a look, @neokore!

Thank you!

**Comment by ana-md** [comment]
After discussing it with @MireyaD and @vdiego we have decided the following: 
1. Disk quota
Copy: `Failed to upload. You’ve exceeded your account’s disk storage limit. Upgrade your plan.`

2. COPY rate limits
- The user (both with Free and Individual plans), should be able to at least save 5-6 datasets from Kepler's UI. This increases UX and we can start measuring. If we recognise too many errors, we could always change the limits again in the future. 
Note: this number has been chosen with really little knowledge from Kepler's users and how many datasets they usually use for creating a map (we have asked Kepler and they have no knowledge at all about their users)
- We stay without retries policy, but we should give an error similar to this one to the user in case they reach the limit: 
`Failed to upload. You've exceeded the number of datasets you can upload in one request.`

Adding @ilbambino here as he will internally discuss with backend if it makes more sense to limit the amount of data IN/OUT instead of the requests (as it is defined right now). Depends on the decision here, we then decide the limits.

**Comment by VictorVelarde** [comment]
Regarding @MireyaD comments 🔝, on feedback to the user: 

> 1. how long will it take?

The time will highly depend on the number & size of the datasets, and network conditions, and it's difficult to estimate upfront. For example, saving 1 map with 1 dataset with ~100K points (NYC taxi pickups) has taken a few seconds on my laptop. 

I would say that for "most cases", we should be in the order of 'seconds', < 1 min, in case that can be useful.

> 2. feedback on progress

I aggree that we should give some feedback to the user when saving / loading. I would say that with the current design in kepler internals, it is not possible to give 'partial updates' (eg. saving dataset 2 from 3...), but I think we should probably display at least something while 'processing', like **"Saving map..." or "Loading map..."**, while the process is being executed, to avoid "loosing the user" 
/cc @neokore

**Comment by neokore** [comment]
1. For bigger datasets and standard broadband speed, it shold take up to 1 minute, as @VictorVelarde says. At least with my computer.
2. I think we could suggest adding a "loading notification" to Uber that could show a notification containing a custom message and a spinner. This way we could show this detailed loading/saving messages. Meanwhile, maybe we could use info notifications and take advantage of its markdown support.

**Comment by VictorVelarde** [comment]
Some work has been done here, specially on Quota. But COPY-related limits are going to be reconsidered, as per https://github.com/CartoDB/cartodb-platform/issues/5946 so I think we should consider closing this issue now, opening a new one for UX if it is required

Thoughts @MireyaD, @neokore ?

**Comment by VictorVelarde** [comment]
We have already added specific messages for limits error, so let's close this!
