### ISSUE TITLE
[Usability] Logging out from CARTO from the Load modal

### ISSUE THREAD

**Issue by ana-md** [CartoDB/kepler.gl#45]
When you login to CARTO from Kepler's UI, you can log out from different places (share, save, load) where the provider box appears. 

Issue: Logging out from the Load modal doesn't work as expected

1. Login from anywhere to your CARTO account (from Kepler's UI)
2. Go to load modal and try to log out.
3. After pressing 2-3 times on the `Logout` it stays active (although user appears as logged out from other modals)
![Screenshot 2020-03-05 at 14 07 05](https://user-images.githubusercontent.com/47864070/75984437-aa418400-5eea-11ea-8745-2c51f2278b95.png)

(Note: If you wait for a while 10-15 seconds, it ends up showing again the login option and it's really logged out, but it's confusing and this behaviour doesn't happen from the save or share modals)

**Comment by ana-md** [comment]
Isa also found it in her [QA](https://docs.google.com/document/d/1HJpnl_2E9GkY3ExsPJWTxax7BX6d6oo2p32ahhf19oE/edit#):

**Title: CARTO logout button in “Add data to map” section**

1. Add data to map
2. Load via storage
3. CARTO
4. Back
5. Logout

**Result:** I don’t see any change in the interface. It looks like I haven’t logged out. But if I go to another tab like “Load Map Using URL” and come back to “Load data via storage” I see that I’m not logged in anymore.

**Expected result:**
The “Logout” and “Connected” texts should disappear
The green stroke around CARTO logo should disappear

**Comment by VictorVelarde** [comment]
Issue created upstream: https://github.com/CartoDB/kepler.gl/issues/45

**Comment by ana-md** [comment]
Shan confirmed that she will fix this and they have moved it in their [Kanban](https://github.com/keplergl/kepler.gl/projects/1#card-34314150).

**Comment by neokore** [comment]
Testing it on Kepler.gl prod it seems to work OK

**Comment by ana-md** [comment]
Seems to work OK to me too! 🚀
