### ISSUE TITLE
[Bug] Saving to CARTO does not save the style. 

### ISSUE THREAD

**Issue by jsanch** [CartoDB/kepler.gl#47]
Try using the earthquake example dataset  and save 

<img width="1433" alt="Screen Shot 2020-03-06 at 12 15 54" src="https://user-images.githubusercontent.com/3717904/76079558-31ebc900-5fa5-11ea-9730-c176cfc730b1.png">

<img width="1440" alt="Screen Shot 2020-03-06 at 12 16 07" src="https://user-images.githubusercontent.com/3717904/76079546-2ac4bb00-5fa5-11ea-969d-7c836fb7c54f.png">

**Comment by ana-md** [comment]
thanks @jsanch for reporting this! 
I found the same problem with exactly the same example

**Comment by jsanch** [comment]
Hi @ana-md , I tried with the SF countour example and I didn't have the problem.

**Comment by ana-md** [comment]
Yes... exactly the same I did and with the same one again 😂
thank you! will keep it in mind for next week

**Comment by ana-md** [comment]
@neokore this is probably what you already had [here](https://github.com/CartoDB/kepler.gl/issues/44#issuecomment-588152317), isn't it?

**Comment by neokore** [comment]
Finally I found what's going on. The issue has to do with Kepler.gl being case sensitive for field names and our tables being saved using lowercase column names. All configurations must match with original column names, if not, it will not apply any configuration.
I've tested a version of toolkit that saves columns names double-quoted to keep uppercase letters and it works great.
Now I'll continue testing to avoid breaking things and create a PR.

**Comment by neokore** [comment]
Fix tested on Kepler.gl, now applying changes and testing on CARTO Dashboard

**Comment by neokore** [comment]
Fix tested on CARTO Dashboard as well, ready for PRs

**Comment by VictorVelarde** [comment]
It should be solved now after a fix we deployed upstream
