### ISSUE TITLE
[Bug] URL parameters change to null after loading public map

### ISSUE THREAD

**Issue by albertoac** [CartoDB/kepler.gl#53]
**Describe the bug**
When loading a public map such as https://kepler.gl/demo/map/carto?mapId=7ffae2c5-9aa3-99e1-4b5d-e227c268526e&owner=albertoag-carto&privateMap=false the url parameter `owner` changes to null, which gives problems in case you copy again the url or you just reload the map as the API url tries to access will be https://null.carto.com....

**To Reproduce**
1. Go to https://kepler.gl/demo/map/carto?mapId=7ffae2c5-9aa3-99e1-4b5d-e227c268526e&owner=albertoag-carto&privateMap=false
2. Wait for the map to load completely (the import modal is closed and you can see the visualization
3. See the url has changed to https://kepler.gl/demo/map/carto?mapId=7ffae2c5-9aa3-99e1-4b5d-e227c268526e&owner=null&privateMap=false (`owner=null`)

**Expected behavior**
The url should not change or, if it changes, it should allow the user to see the same content as is visualizing at that moment.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Tested on Chrome 80 & Brave 1.3

**Comment by neokore** [comment]
PR merged, now you can test it at https://kepler.gl/demo

**Comment by albertoac** [comment]
Seems to be working fine! I close the ticket
