### ISSUE TITLE
[Bug] Normal workflow doesn't allow the user to signup

### ISSUE THREAD

**Issue by albertoac** [CartoDB/kepler.gl#55]
**Describe the bug**
While talking with @ana-md , we found that is not possible to signup into carto from kepler using a normal workflow. The problem is that when you click on CARTO, the popup is open in a very small size, similar to a mobile view. In that mobile view there's no signup link, so if the user doesn't have an account it's only solution is to close the modal (or realize that if he makes it bigger it can actually do a signup)

**To Reproduce**
1. Go to https://kepler.gl/demo (in incognito mode preferably, so your account doesn't affect)
2. Create a new map
3. Click on save to CARTO
4. See that the pop up open is 600x600px, so it falls into the mobile view. It will need at least 800px width in order to show the desktop view.

**Expected behavior**
As the signup process is available in mobile view, I think the easiest way to solve is to add the link to the signup in the mobile view so it also appears in the modal.

**Screenshots**
![image](https://user-images.githubusercontent.com/4774531/76339783-d7cb6a80-62fa-11ea-8f09-f982eccb35df.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14 (screen resolution 1680x1050px)
 - Browser: Brave

**Comment by VictorVelarde** [comment]
Fixed!

This is how it looks now
![image](https://user-images.githubusercontent.com/458196/76364404-605f0080-6325-11ea-9064-61930397eeee.png)

**Comment by ana-md** [comment]
Thank you @albertoac and @VictorVelarde !!
