### ISSUE TITLE
Create mockups for the first meeting with Kepler's PM.

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/kepler.gl#8]
**Objective**
**Deadline**: `September 18th` (meeting with the PM from Kepler)

To create some mockups for the simplest user flows of the following features: 
- Sharing your maps using CARTO.
- Storage Engine.

**Comment by ana-md** [comment]
The final result of this issue can be found here: https://projects.invisionapp.com/share/TPTSVDX2KF5#/screens/384524982_Home
